spring:
  datasource:
    username: loanadmin
    password: '{cipher}AQAsaOo8qdU0W4PaJOGjGsVlCHimHXGjvukzIIqwcQwrFKeXtjWNVvYR/IAdnjn9fzlxD79I5Z+MwbLC588eJMXxxtTK4qCKHOYZccRr4SOlp5TELkxpBdKi55r4vPPMo9437J9NV2m9MnzJBz73cuTIu+us2L2BTbqYoWybN85cufKXZPo5HAUvqqmsyqvTJzR3/LOmlRN4iB/+l+Ag2SfnCB/BH32WiH/VuzA3ezKdOev0cavSuBVIsGPsTB+mObz4Q0WxmcEirOAIvI1+iuSdaJMeU5q94By+q6BMTNCksnhWpk+73NUXpvWcMwxIloANlXa8DFwWpxOWCZAGrFXwcf9UPh9QaHFlCFOuaGDL6OHu535OkIRy2sllitOvpoA='
    
